dcmdb/dictionary/views.py
from __future__ import print_function

import math
from sqlalchemy import or_, and_
from sqlalchemy import func
from flask import Blueprint, render_template, request, jsonify

from ..models import DataElement

blueprint = Blueprint("dictionary", __name__,
                    url_prefix="/dictionary", template_folder="templates",
                    static_folder="static")

@blueprint.route('/')
def search(query=None):
    return render_template('ded_search.html')

@blueprint.route('/query/')
@blueprint.route('/query/<path:query>/')
def query(query=None):
    data_element_results = None
    page = None
    de_per_page = 20.0

    if request.values.get("page"):
        page = int(request.values.get("page"))

    request_query = request.values.get("query")
    if request_query:
        query = request_query

    if query is None:
        return jsonify({ "data_elements": [], "num_results": 0 })

    try:
        if "," in query:
            params = query.split(",")
            query_items = []
            for item in params:
                if "x" in item:
                    query_items.append(int(item, 16))
                else:
                    query_items.append(int(item))

            data_element_results = DataElement.query \
                                    .filter(and_(query_items[0]>= DataElement.min_group,
                                                 query_items[0]<= DataElement.max_group,
                                                 query_items[1]>= DataElement.min_element,
                                                 query_items[1]<= DataElement.max_element)).all()
        else:
            if "x" in query:
                query = int(query, 16)
            else:
                query = int(query)

            data_element_results = DataElement.query \
                    .filter(or_(and_(query>=DataElement.min_group,
                                     query<=DataElement.max_group),
                                and_(query>=DataElement.min_element,
                                     query<=DataElement.max_element))
                    ).all()
    except ValueError:
        data_element_results = DataElement.query.filter(
                                func.lower(DataElement.name).like('%' + query.lower() + '%')).all()

    data_elements = [element.json for element in data_element_results]

    response = {
        "data_elements": data_elements,
        "num_results": len(data_elements)
    }

    if page is not None:
        last_page = int(math.ceil(len(data_element_results) / de_per_page))
        page_min = (int(page) - 1) * de_per_page
        if page == 1:
            page_min = 0
        page_max = page_min + de_per_page
        response["pages"] = [page + 1 for page in xrange(last_page)]
        response["data_elements"] = data_elements[int(page_min):int(page_max)]

    return jsonify(response)

dcmdb/explorer/views.py
from __future__ import print_function

from flask import Blueprint, render_template, request, jsonify

blueprint = Blueprint("explorer", __name__,
                    url_prefix="/explorer", template_folder="templates",
                    static_folder="static")

@blueprint.route('/')
def explore():
    return render_template('explore.html')

dcmdb/uploader/views.py
from __future__ import print_function

from flask import Blueprint, render_template, request, jsonify

from ..helpers import upload_file

blueprint = Blueprint("uploader", __name__,
                    url_prefix="/uploader", template_folder="templates",
                    static_folder="static")

@blueprint.route('/')
def upload():
    return render_template('upload.html')

@blueprint.route('/handle/', methods=['GET', 'POST'])
def handle():
    file_to_upload = request.files["files[]"]
    fname = upload_file(file_to_upload)

    #db.session.add(model)
    #db.session.commit()

    response = {
        "name": fname,
    }

    return jsonify(**response)

dcmdb/templates/about.html
{% extends "base.html" %}

{% block content %}
<div class="page-header">
    <h3>About dcmdb <small>Last updated 10/26/2014</small></h3>
</div>
<div class="row">
	<div class="col-md-12">

		This website was developed by <a href="http://neurosnap.net">Eric Bower</a>.  The mission of this service is to create a learning resource and
		development toolkit for developers and the curious.

		<br />
		<hr />
		<h4><small>Toolkit</small></h4>
		As a student studying neuroscience, I found it rather difficult to find a common platform for <a href="http://en.wikipedia.org/wiki/DICOM">Digital Imaging and Communications in Medicine (DICOM)</a> tools to facilitate an understanding of how the most common, prominent diagnostic file operates.  One of my goals with this project is to create a platform that at its core is a learning resource that provides tools and utilities to anyone interested in this technology.

		<br /><br />
		<h4><small>Collaboration</small></h4>

		If you are interested in helping, the source code is hosted on <a href="https://github.com/neurosnap/dcmdb-flask"><i class="fa fa-github"></i> Github</a>, feel free to have a look.  Any suggestions, comments, or critcisms are greatly appreciated.

		<br /><br />
		<h4><small>Open-Source all the way down</small></h4>

		This project was developed in <a href="http://www.python.org/">Python</a>, the <a href="http://flask.pocoo.org//">Flask framework</a>, and <a href="http://www.postgresql.org/">Postgresql</a>. The production server is hosted by <a href="http://aws.amazon.com/ec2/">Amazon</a> on an Ubuntu EC2 virtualized server. It uses <a href="http://gunicorn.org/">Gunicorn</a> as the WSGI HTTP Server and <a href="http://wiki.nginx.org/Main">NGINX</a> as the Proxy HTTP Server.

		<br /><br />
		<h5><a href="https://github.com/neurosnap/mudicom"><i class="fa fa-github"></i> Mudicom</a></h5>

		I created mudicom to help facilitate the needs of this web service.  I hope, in time, it will be good enough to
		replace all of the current python packages for DICOM files.

		It depends on the open-source C++ application for DICOM files:
		<a href="http://sourceforge.net/projects/gdcm/">Grassroots DICOM</a>

		<hr />

	</div>
</div>
{% endblock %}

dcmdb/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="Content-type" content="text/html;charset=UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
		<meta name=”description” content=”DICOM toolkit”>

		<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
		<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
		<link href="{{ url_for('static', filename='darkly.min.css') }}" rel="stylesheet">
		<link href="{{ url_for('static', filename='base.css') }}" rel="stylesheet">
		{% block css %}{% endblock %}

		<title>DCMDB | DICOM Toolkit</title>
	</head>
	<body>
		<nav class="navbar navbar-default" role="navigation">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="/">dcmdb</a>
			</div>
			<div class="collapse navbar-collapse navbar-ex1-collapse">
				<ul class="nav navbar-nav">
					<li><a href="{{ url_for('dictionary.search') }}"><i class="fa fa-book"></i> Dictionary</a></li>
					{% if g.debug %}
					<li><a href="{{ url_for('explorer.explore') }}"><i class="fa fa-th-large"></i> Explorer</a></li>
					<li><a href="{{ url_for('uploader.upload') }}"><i class="fa fa-edit"></i> Editor</a></li>
					<li><a href="{{ url_for('uploader.upload') }}"><i class="fa fa-bug"></i> Validator</a></li>
					<li><a href="{{ url_for('uploader.upload') }}"><i class="fa fa-bug"></i> Anonymizer</a></li>
					<li><a href="{{ url_for('uploader.upload') }}"><i class="fa fa-cloud-upload"></i> Uploader</a></li>
					{% endif %}
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<i class="fa fa-ellipsis-v"></i> About <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><a href="{{ url_for('about') }}"><span class="glyphicon glyphicon-headphones"></span> dcmdb</a></li>
							<li><a href="{{ url_for('dicom') }}"><i class="fa fa-file"></i> What is DICOM?</a></li>
							<li><a href="{{ url_for('tos') }}"><i class="fa fa-asterisk"></i> Terms of Service</a></li>
							<li><a href="{{ url_for('privacy') }}"><i class="fa fa-send"></i> Privacy Policy</a></li>
							<li><a href="{{ url_for('transfer_syntax') }}"><i class="fa fa-barcode"></i> Transfer Syntax</a></li>
						</ul>
					</li>
				</ul>
			</div>
		</nav>
		<div id="content" class="container">
			{% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                    <div class="alert alert-{{category}} alert-dismissable" style="margin: 8px 0px;">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                           &times;
                        </button>
                        {{ message }}
                    </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

			{% block content %}{% endblock %}

			<br />
			<br />
		</div>
		<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
		<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
		<script src="{{ url_for('static', filename='base.js')  }}"></script>
		{% block js %}{% endblock %}
	</body>
</html>

dcmdb/templates/dicom.html
{% extends "base.html" %}

{% block content %}
<div class="page-header">
	<h3>Digital Imaging and Communications in Medicine (DICOM) <small>Last updated 11/18/2013</small></h3>
</div>
<div class="row">
	<div class="col-md-12">
		DICOM files are the means by which the medical community communicates medical imaging data.  It creates a standard to transmit medical images in a complex and dynamic environment of cutting-edge, innovative technologies.  The standard is maintained by the <a href="http://www.medicalimaging.org/">Medical Imaging and Technology Alliance (MITA)</a>,
		which is a division of the <a href="http://www.nema.org/">National Electrical Manufacturers Association (NEMA)</a>.  The DICOM standard is freely available <a href="http://medical.nema.org/standard.html">here</a>.
		<br />
		<hr />
		<h3><small>A Brief History</small></h3>
		<a href="http://www.cancer.gov/cancertopics/factsheet/detection/CT">Computed Tomography (CT)</a> emerged as a medical diagnostic utility in the 1970s and with it other influential modalities.  
		The <a href="http://www.acr.org/">American College of Radiology (ACR)</a> and 
		NEMA formed a jount committee in 1983 to create a standard that adhered to certain principles that are necessary for succint transmission of medical images.
		<br />
		<blockquote>
			<p>
				<ul>
				<li> Promote communication of digital image information, regardless of device manufacturer </li>
				<li> Facilitate the development and expansion of picture archiving and communication systems (PACS) that can also interface with other systems of hospital information </li>
				<li> Allow the creation of diagnostic information data bases that can be interrogated by a wide variety of devices distributed geographically. </li>
				</ul>
			</p>
			<small><a href="http://medical.nema.org/Dicom/2011/11_01pu.pdf">2011 DICOM Standard</a></small>
		</blockquote>
		<h3><small>A Functional Overview</small></h3>
		The DICOM standard was designed to set minimum software commands, consistent data organization, and interfacing with medical imaging hardware.  
		The principles that were necessary for a medical imaging standard are the following: <br /><br />
			<ul>
				<li>Ability to interface with computer networks</li>
				<li>Ability to be functional offline</li>
				<li>Specifies how data should be communicated between devices, computers, and personel</li>
				<li>Specifies a multipart document: header (patient, study, series) data and image data</li>
				<li>Specifies explicit Information Objects for images, waveforms, and printing</li>
				<li>Specifies strict definitions and relational organization of Information Objects</li>
			</ul>
		A DICOM file is broken up into objects that are perfectly relational.  A <strong>patient</strong> can have many medical scans conducted throughout their lifetime, 
		therefore he or she can have multiple <strong>studies</strong> performed on them.  Within any single study, the patient could be asked to change positions,
		which correspond to <strong>series</strong>.  Within any single series, there are multiple <strong>images</strong> being captured by the medical imaging hardware.
		<h3><small>A Technical Overview</small></h3>
		As was mentioned above, a DICOM file contains multiple objects that relate to patient, study, series, and image information.  These are defined by the following Unique Identifiers (UID):
		<br /><br />
		<ul>
			<li><strong>Patient</strong>: Patient ID</li>
			<li><strong>Study</strong>: Study Instance UID</li>
			<li><strong>Series</strong>: Series Instance UID</li>
			<li><strong>Image</strong>: SOP Instance UID</li>
		</ul>
		A patient can have multiple studies; a study can have multiple series; a series can have multiple images, linked together relationally by the keys mentioned above.  This is how I have organized the 
		relational database (postgreSQL) for this website -- excluding patient data.  Before any file is uploaded to our servers, the patient data is anonymized.
		<hr />
	</div>
</div>
{% endblock %}

dcmdb/templates/index.html
{% extends "base.html" %}

{% block css %}
<link href="{{ url_for('static', filename='index.css') }}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="jumbotron">
    <h1><span class="glyphicon glyphicon-headphones"></span> dcmdb.org</h1>
    <p>
        An open-source webservice that provides a range of DICOM development utilities.
        Search our image repository or data element dictionary.
        Edit, validate, or anonymize DICOM files with ease.
    </p>
    <p>
        The mission of this service is to create a set of utilities that
        medical technicians can use to view, edit, anonymize, validate,
        and lookup DICOM files or images with a suite of easy to use utilities and a
        repository of anonymous medical diagnotic images. With this service we also
        wish to create a social platform for discussion, teaching, and learning.
    </p>

    <h3>Progress</h3>
    <p>
        My primary goal with the launch of this site is to periodically
        publish new tools as they become available.
    </p>

    <h3>Upcoming</h3>
    <ul>
        <li><i class="fa fa-check"></i> DICOM Data Element Dictionary</li>
        <li><i class="fa fa-circle-o"></i> DICOM Editor</li>
        <li><i class="fa fa-circle-o"></i> DICOM Validator</li>
        <li><i class="fa fa-circle-o"></i> DICOM Anonymizer</li>
        <li><i class="fa fa-circle-o"></i> DICOM Image Anonymizer</li>
        <li><i class="fa fa-circle-o"></i> DICOM Image Repository</li>
    </ul>

    <p>
        <a class="btn btn-primary btn-lg" role="button" href="{{ url_for('dictionary.search') }}">
            <span class="glyphicon glyphicon-th"></span> Getting Started</a>
    </p>
</div>
{% endblock %}

dcmdb/templates/privacy.html
{% extends "base.html" %}

{% block content %}
<div class="page-header">
	<h3>Privacy Policy <small>Last updated 11/18/2013</small></h3>
</div>

<div class="row">
	<div class="col-md-12">
		Our privacy policy applies to information we collect when you use or access our website, application, or just interact with us. We may change this privacy policy from time to time. Whenever we make changes to this privacy policy, the changes are effective immediately after we post the revised privacy policy (as indicated by revising the date at the top of our privacy policy). We encourage you to review our privacy policy whenever you access our services to stay informed about our information practices and the ways you can help protect your privacy.<br />

		<h3>Collection of Information<h3>

		<h3><small>Information You Provide to Us</small></h3>

		We collect information you provide directly to us. For example, we collect information when you participate in any interactive features of our services, upload a file, request customer support, provide any contact or identifying information or otherwise communicate with us. The types of information we may collect include your name, email address, IP address, and other contact or identifying information you choose to provide.

		<h3><small>Information We Collect Automatically When You Use the Services</small></h3>

		When you access or use our services, we automatically collect information about you, including:<br />

		<ul>
			<li><strong>Log Information</strong>: We log information about your use of our services, including the type of browser you use, access times, pages viewed, your IP address and the page you visited before navigating to our services.</li>
			<li><strong>Device Information</strong>: We collect information about the computer you use to access our services.</li>
		</ul>

		For more details about how we collect information, including details about cookies and how to disable them, please see "Your Information Choices" below.

		<h3>Information We Collect From Other Sources</h3>

		In order to provide you with access to the Service, or to provide you with better service in general, we may combine information obtained from other sources (for example, a third-party service whose application you have authorized or used to sign in) and combine that with information we collect through our services.

		<h3>Use of Information</h3>

		We use information about you for various purposes, including to:<br />

		<ul>
			<li>Provide, maintain and improve our services;</li>
			<li>Provide services you request, process transactions and to send you related information;</li>
			<li>Send you technical notices, updates, security alerts and support and administrative messages;</li>
			<li>Respond to your comments, questions and requests and provide customer service;</li>
			<li>Communicate with you about news and information related to our service;</li>
			<li>Monitor and analyze trends, usage and activities in connection with our services; and</li>
			<li>Personalize and improve our services.</li>
		</ul>

		By accessing and using our services, you consent to the processing and transfer of your information in and to the United States and other countries.<br />

		<h3>Sharing of Information</h3>

		We may share personal information about you as follows:<br />

		<ul>
			<li>With third party vendors and other service providers who need access to your information to carry out work on our behalf, such as Google Analytics;</li>
			<li>If we believe disclosure is reasonably necessary to comply with any applicable law, regulation, legal process or governmental request;</li>
			<li>To enforce applicable user agreements or policies, including our <a href="/main/tos">Terms of Service</a>; and to protect us, our users or the public from harm or illegal activities;</li>
			<li>In connection with any merger, sale of dcmdb assets, financing or acquisition of all or a portion of our business to another company; and</li>
			<li>If we notify you through our services (or in our privacy policy) that the information you provide will be shared in a particular manner and you provide such information.</li>
		</ul>

		We may also share aggregated or anonymized information that does not directly identify you.

		<h3>Third Party Analytics</h3>

		We may allow third parties to provide analytics services. These third parties may use cookies, web beacons and other technologies to collect information about your use of the services and other websites, including your IP address, web browser, pages viewed, time spent on pages, links clicked and conversion information. This information may be used by us and third parties to, among other things, analyze and track data, determine the popularity of certain content and other websites and better understand your online activity. Our privacy policy does not apply to, and we are not responsible for, third party cookies, web beacons or other tracking technologies and we encourage you to check the privacy policies of these third parties to learn more about their privacy practices.

		<h3>Security</h3>

		We take reasonable measures to help protect personal information from loss, theft, misuse and unauthorized access, disclosure, alteration and destruction.

		<h3>Your Information Choices</h3>

		<h3><small>Cookies</small></h3>

		Most web browsers are set to accept cookies by default. If you prefer, you can usually choose to set your browser to remove or reject browser cookies. Please note that if you choose to remove or reject cookies, this could affect the availability and functionality of our services.

		<h3>Contact Us</h3>

		If you have any questions about this privacy policy, please contact the <a href="mailto:dcmdb.webmaster@gmail.com">webmaster</a>.

		<hr />
	</div>
</div>
{% endblock %}

dcmdb/templates/search.html
{% extends "base.html" %}

{% block content %}
<div class="row">
	<div class="col-md-2">
		<div class="input-group">
			<h5>Search</h5>
		</div>
	</div>
	<div class="col-md-7">
		<form role="search" method="POST" action="/main/search">
			<div class="col-md-10">
				<div class="form-group">
					<input type="text" class="form-control" placeholder="Find a data element" value="{{ query }}">
				</div>
			</div>
			<div class="col-md-2">
				<button class="btn btn-primary" type="submit">Search</button>
			</div>
		</form>
	</div>
</div>

<hr />

{% endblock %}

dcmdb/templates/transfer_syntax.html
{% extends "base.html" %}

{% block content %}
<div class="page-header">
	<h3>Transfer Syntax <small>Last Updated 11/01/2013</small></h3>
</div>
<div class="row">
	<div class="col-md-12">
		<blockquote>
			<p>
				A transfer syntax is a set of encoding rules that allow Application Entities to unambiguously negotiate the encoding techniques (e.g., Data Element structure, byte ordering, compression) they are able to support, thereby allowing these Application Entities to communicate. 
			</p>
			<small><a href="http://www.dabsoft.ch/dicom/5/3.10/">DICOM Standard 3.10</a></small>
		</blockquote> 
		The Transfer Syntax UID is the unique identifier used as a tag in the DICOM standard to determine the type of encoding principles used for any given DICOM file.  The Transfer Syntax UID is in the file DICOM Tag field (0002,0010).  <span class="text-success">The transfer syntaxes highlighted in green</span> are currently supported by dcmdb, <span class="text-danger">the ones in red</span> are not supported.
	</div>
</div>
<hr />
<div class="row">
	<div class="col-md-12">
		<table class="table table-hover">
			<thead>
				<th>Transfer Syntax UID</th>
				<th>Description</th>
			</thead>
			<tbody>
				<tr class="success">
					<td>1.2.840.10008.1.2</td>
					<td>Implicit VR - Little Endian</td>
				</tr>
				<tr class="success">
					<td>1.2.840.10008.1.2.1</td>
					<td>Explicit VR - Little Endian</td>
				</tr>
				<tr class="success">
					<td>1.2.840.10008.1.2.1.99</td>
					<td>Deflated Explicit VR - Little Endian</td>
				</tr>
				<tr class="success">
					<td>1.2.840.10008.1.2.2</td>
					<td>Explicit VR - Big Endian</td>
				</tr>
				<tr class="success">
					<td>1.2.840.113619.5.2</td>
					<td>Implicit VR - Big Endian (G.E Private)</td>
				</tr>
				<tr class="success">
					<td>1.2.840.10008.1.2.5</td>
					<td>Run Length Encoding, Lossless</td>
				</tr>
				<tr class="success">
					<td>1.2.840.10008.1.2.4.50</td>
					<td>JPEG Baseline (Process 1)</td>
				</tr>
				<tr class="success">
					<td>1.2.840.10008.1.2.4.51</td>
					<td>JPEG Extended (Process 2 & 4)</td>
				</tr>
				<tr class="success">
					<td>1.2.840.10008.1.2.4.57</td>
					<td>JPEG Lossless, Non-Hierarchical (Process 14)</td>
				</tr>
				<tr class="success">
					<td>1.2.840.10008.1.2.4.70</td>
					<td>JPEG Lossless, Hierarchical, First-Order Prediction (Process 14, [Selection Value 1])</td>
				</tr>
				<tr class="success">
					<td>1.2.840.10008.1.2.4.90</td>
					<td>JPEG 2000 Image Compression (Lossless Only)</td>
				</tr>
				<tr class="success">
					<td>1.2.840.10008.1.2.4.91</td>
					<td>JPEG 2000 Image Compression</td>
				</tr>
				<tr class="danger">
					<td>1.2.840.10008.1.2.4.52</td>
					<td>JPEG Extended (Process 3 & 5)</td>
				</tr>
				<tr class="danger">
					<td>1.2.840.10008.1.2.4.53</td>
					<td>JPEG Spectral Selection, Non-Hierarchical (Process 6 & 8)</td>
				</tr>
				<tr class="danger">
					<td>1.2.840.10008.1.2.4.54</td>
					<td>JPEG Spectral Selection, Non-Hierarchical (Process 7 & 9)</td>
				</tr>
				<tr class="danger">
					<td>1.2.840.10008.1.2.4.55</td>
					<td>JPEG Full Progression, Non-Hierarchical (Process 10 & 12)</td>
				</tr>
				<tr class="danger">
					<td>1.2.840.10008.1.2.4.56</td>
					<td>JPEG Full Progression, Non-Hierarchical (Process 11 & 13)</td>
				</tr>
				<tr class="danger">
					<td>1.2.840.10008.1.2.4.59</td>
					<td>JPEG Extended, Hierarchical (Process 16 & 18)</td>
				</tr>
				<tr class="danger">
					<td>1.2.840.10008.1.2.4.60</td>
					<td>JPEG Extended, Hierarchical (Process 17 & 19)</td>
				</tr>
				<tr class="danger">
					<td>1.2.840.10008.1.2.4.61</td>
					<td>JPEG Spectral Selection, Hierarchical (Process 20 & 22)</td>
				</tr>
				<tr class="danger">
					<td>1.2.840.10008.1.2.4.62</td>
					<td>JPEG Spectral Selection, Hierarchical (Process 21 & 23)</td>
				</tr>
				<tr class="danger">
					<td>1.2.840.10008.1.2.4.63</td>
					<td>JPEG Full Progression, Hierarchical (Process 24 & 26)</td>
				</tr>
				<tr class="danger">
					<td>1.2.840.10008.1.2.4.64</td>
					<td>JPEG Full Progression, Hierarchical (Process 25 & 27)</td>
				</tr>
				<tr class="danger">
					<td>1.2.840.10008.1.2.4.80 (partial)</td>
					<td>JPEG-LS Lossless Image Compression</td>
				</tr>
				<tr class="danger">
					<td>1.2.840.10008.1.2.4.81 (partial)</td>
					<td>JPEG-LS Lossy (Near-Lossless) Image Compression</td>
				</tr>
				<tr class="danger">
					<td>1.2.840.10008.1.2.4.100 (partial)</td>
					<td>MPEG2 Main Profile @ Main Level</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>
<hr />
{% endblock %}

dcmdb/templates/uc.html
{% extends "base.html" %}

{% block content %}
    <div class="jumbotron">
        <h1><span class="glyphicon glyphicon-headphones"></span> dcmdb.org</h1>
        <p>
            An open-source webservice that provides a range of DICOM development utilities.
            Search our image repository or data element dictionary.
            Edit, validate, or anonymize DICOM files with ease.
        </p>
        <p>
            The mission of this service is to create a set of utilities that
            medical technicians can use to view, edit, anonymize, validate,
            and lookup DICOM files or images with a suite of easy to use utilities and a
            repository of anonymous medical diagnotic images. With this service we also
            wish to create a social platform for discussion, teaching, and learning.
        </p>
        <p>
            Launch Date:  Before 2015 <br />
            Questions?  <a href="mailto:neurosnap@gmail.com">Contact me</a>
        </p>
    </div>
{% endblock %}

dcmdb/templates/uc_index.html
{% extends "under_construction.html" %}

{% block js %}
{% endblock %}

{% block content %}
	<div class="jumbotron">
		<h1><span class="glyphicon glyphicon-headphones"></span> dcmdb</h1>
		<p>
			An open-source, anonymous, medical diagnostic imaging repository, search engine, and learning utility.
		</p>
		<p>
            Launch Date:  November 9, 2013 <br />
            Questions?  <a href="mailto:dcmdb.webmaster@gmail.com">Contact me</a>
		</p>
    </div>
{% endblock %}